### PR TITLE
Add issue data processing handler

### PR DESCRIPTION
**Pull request by Createsnow**

### CODE REVIEW

**Comment by XinShuYang** [comment]
@Createsnow Please add commit message, signature and document for script usage. You can refer to this commit https://github.com/antrea-io/antrea/pull/5502/commits/c313e7c86706311b4518b9caa12929a6df029d5a

**Comment by Createsnow** [comment]
okay

**Comment by XinShuYang** [comment]
@Createsnow I found some issue labels in dataset were wrong. For example, `Figure out a stable path for SSL installation in install-ovs.ps1` . The label of this issue should be `windows` and `bug` not `api`.https://github.com/antrea-io/antrea/issues/5479  Could you double check?

**Comment by Createsnow** [comment]
> @Createsnow I found some issue labels in dataset were wrong. For example, `Figure out a stable path for SSL installation in install-ovs.ps1` . The label of this issue should be `windows` and `bug` not `api`.[antrea-io#5479](https://github.com/antrea-io/antrea/issues/5479) Could you double check?

okay. I will check again with reference to the document tomorrow.

**Pull request closed without merging**
